# Smithery test configuration for MCP server scanning
version: "1.0"
name: "monster-jobs-mcp-server"
description: "Test configuration for Monster Jobs MCP Server"

tests:
  - name: "health_check"
    type: "http"
    endpoint: "/health"
    method: "GET"
    expected:
      status: 200
      response:
        status: "healthy"
        service: "Monster Jobs MCP Server"
        version: "1.0.0"

  - name: "ping_test"
    type: "http"
    endpoint: "/ping"
    method: "GET"
    expected:
      status: 200
      response:
        status: "pong"

  - name: "ready_check"
    type: "http"
    endpoint: "/ready"
    method: "GET"
    expected:
      status: 200
      response:
        status: "ready"

  - name: "mcp_config"
    type: "http"
    endpoint: "/.well-known/mcp-config"
    method: "GET"
    expected:
      status: 200
      response:
        serverInfo:
          name: "monster-jobs-mcp-server"
          version: "1.0.0"

  - name: "mcp_capabilities"
    type: "http"
    endpoint: "/mcp/capabilities"
    method: "GET"
    expected:
      status: 200
      response:
        protocolVersion: "2024-11-05"
        serverInfo:
          name: "monster-jobs-mcp-server"

  - name: "mcp_initialize"
    type: "jsonrpc"
    endpoint: "/mcp"
    method: "POST"
    payload:
      jsonrpc: "2.0"
      method: "initialize"
      params:
        protocolVersion: "2024-11-05"
        capabilities: {}
      id: 1
    expected:
      status: 200
      response:
        jsonrpc: "2.0"
        result:
          protocolVersion: "2024-11-05"
          serverInfo:
            name: "monster-jobs-mcp-server"

  - name: "mcp_tools_list"
    type: "jsonrpc"
    endpoint: "/mcp"
    method: "POST"
    payload:
      jsonrpc: "2.0"
      method: "tools/list"
      params: {}
      id: 2
    expected:
      status: 200
      response:
        jsonrpc: "2.0"
        result:
          tools:
            - name: "search_jobs"

  - name: "mcp_resources_list"
    type: "jsonrpc"
    endpoint: "/mcp"
    method: "POST"
    payload:
      jsonrpc: "2.0"
      method: "resources/list"
      params: {}
      id: 3
    expected:
      status: 200
      response:
        jsonrpc: "2.0"
        result:
          resources:
            - uri: "monster://jobs/search"

scan_config:
  timeout: 30
  retry_attempts: 3
  retry_delay: 2
  validate_json: true
  check_protocol_compliance: true

endpoints:
  primary: "/mcp/scan"
  fallback:
    - "/mcp/capabilities"
    - "/smithery"
    - "/.well-known/mcp-config"
    - "/scan"

validation:
  required_endpoints:
    - "/health"
    - "/mcp"
    - "/.well-known/mcp-config"
  required_methods:
    - "initialize"
    - "tools/list"
    - "resources/list"
  protocol_version: "2024-11-05"